In [178]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [179]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [180]:
data.drop(['RowNumber','CustomerId','Surname'],axis = 1,inplace = True)

In [181]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [182]:
encoder_gender = LabelEncoder()

data['Gender'] = encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [183]:
from sklearn.preprocessing import OneHotEncoder

encode_geography = OneHotEncoder()

var = encode_geography.fit_transform(data[['Geography']]).toarray()
var

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [184]:
geo_df = pd.DataFrame(var,columns = encode_geography.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [185]:
data = pd.concat([geo_df,data],axis=1)

In [186]:
data.head()

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1.0,0.0,0.0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,0.0,0.0,1.0,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,1.0,0.0,0.0,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,1.0,0.0,0.0,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,0.0,0.0,1.0,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [187]:
data.drop(['Geography'],axis=1,inplace=True)

In [188]:
data.head()

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1.0,0.0,0.0,619,0,42,2,0.00,1,1,1,101348.88,1
1,0.0,0.0,1.0,608,0,41,1,83807.86,1,0,1,112542.58,0
2,1.0,0.0,0.0,502,0,42,8,159660.80,3,1,0,113931.57,1
3,1.0,0.0,0.0,699,0,39,1,0.00,2,0,0,93826.63,0
4,0.0,0.0,1.0,850,0,43,2,125510.82,1,1,1,79084.10,0

In [189]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Geography_France   10000 non-null  float64
 1   Geography_Germany  10000 non-null  float64
 2   Geography_Spain    10000 non-null  float64
 3   CreditScore        10000 non-null  int64
 4   Gender             10000 non-null  int64
 5   Age                10000 non-null  int64
 6   Tenure             10000 non-null  int64
 7   Balance            10000 non-null  float64
 8   NumOfProducts      10000 non-null  int64
 9   HasCrCard          10000 non-null  int64
 10  IsActiveMember     10000 non-null  int64
 11  EstimatedSalary    10000 non-null  float64
 12  Exited             10000 non-null  int64
dtypes: float64(5), int64(8)
memory usage: 1015.8 KB

In [190]:
## Save encoders and scaler

with open('Label_encoder_gender.pkl','wb') as file:
    pickle.dump(encoder_gender,file)

In [191]:
with open('OneHotEncoder_geography.pkl','wb') as file:
    pickle.dump(encode_geography,file)

In [192]:
X=data.drop(['Exited'],axis=1)
y = data['Exited']

In [193]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [194]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [195]:
X_train

array([[ 0.998002  , -0.5761528 , -0.57700814, ...,  0.64807894,
         0.96892697, -1.24141718],
       [ 0.998002  , -0.5761528 , -0.57700814, ...,  0.64807894,
         0.96892697, -0.83893014],
       [-1.002002  , -0.5761528 ,  1.73307782, ..., -1.54302191,
        -1.03206953, -0.35176236],
       ...,
       [ 0.998002  , -0.5761528 , -0.57700814, ..., -1.54302191,
        -1.03206953, -0.13276205],
       [ 0.998002  , -0.5761528 , -0.57700814, ...,  0.64807894,
        -1.03206953, -0.04086253],
       [-1.002002  ,  1.73565068, -0.57700814, ...,  0.64807894,
         0.96892697, -0.80427439]], shape=(9000, 12))

In [196]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN

In [197]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [198]:
X_train.shape,X_train.shape[1]

((9000, 12), 12)

In [199]:
model = Sequential([
    Dense(64,activation = 'relu',input_shape = (X_train.shape[1],)), #Hideen Layer 1
    Dense(32,activation = 'relu'), #HL2
    Dense(1,activation = 'sigmoid')
    
])

c:\Users\11c16\anaconda3\envs\hcl_venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [200]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [201]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [202]:
## compile model

model.compile(optimizer ="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [203]:
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir,histogram_freq=1)

In [204]:
## Early stopping (epochs control)
early_stopping_callback =EarlyStopping(monitor = 'val_loss',patience = 5,restore_best_weights=True)

In [205]:
##Train model
history = model.fit(
    X_train,y_train,validation_data = (X_test,y_test),
    epochs = 100,
    callbacks = [tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8081 - loss: 0.4481 - val_accuracy: 0.8320 - val_loss: 0.3919
Epoch 2/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8458 - loss: 0.3786 - val_accuracy: 0.8540 - val_loss: 0.3583
Epoch 3/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8540 - loss: 0.3504 - val_accuracy: 0.8660 - val_loss: 0.3435
Epoch 4/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3422 - val_accuracy: 0.8660 - val_loss: 0.3382
Epoch 5/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8620 - loss: 0.3377 - val_accuracy: 0.8660 - val_loss: 0.3413
Epoch 6/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8636 - loss: 0.3350 - val_accuracy: 0.8660 - val_loss: 0.3354
Epoch 7/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8629 - loss: 0.3321 - val_accuracy: 0.8660 - val_loss: 0.3338
Epoch 8/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3303 - val_accuracy: 0.8670 - val_loss: 0.3342
Epoch 9/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8649 - loss: 0.3278 - val_accuracy: 0.8550 - val_loss: 0.3360
Epoch 10/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8643 - loss: 0.3259 - val_accuracy: 0.8580 - val_loss: 0.3331
Epoch 11/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8666 - loss: 0.3254 - val_accuracy: 0.8580 - val_loss: 0.3367
Epoch 12/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8660 - loss: 0.3226 - val_accuracy: 0.8590 - val_loss: 0.3323
Epoch 13/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8663 - loss: 0.3205 - val_accuracy: 0.8580 - val_loss: 0.3345
Epoch 14/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8660 - loss: 0.3204 - val_accuracy: 0.8680 - val_loss: 0.3316
Epoch 15/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8683 - loss: 0.3189 - val_accuracy: 0.8620 - val_loss: 0.3322
Epoch 16/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8669 - loss: 0.3174 - val_accuracy: 0.8650 - val_loss: 0.3329
Epoch 17/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8671 - loss: 0.3156 - val_accuracy: 0.8560 - val_loss: 0.3354
Epoch 18/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8683 - loss: 0.3153 - val_accuracy: 0.8570 - val_loss: 0.3381
Epoch 19/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8709 - loss: 0.3135 - val_accuracy: 0.8540 - val_loss: 0.3422

In [206]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [207]:
%reload_ext tensorboard

In [208]:
%tensorboard --logdir logs

Reusing TensorBoard on port 6007 (pid 29440), started 0:13:50 ago. (Use '!kill 29440' to kill it.)

In [209]:
##Load pickle file